[pytest]
addopts = -v --tb=short --alluredir=allure-results
testpaths = tests
markers =
    smoke: быстрые тесты для критического функционала
    regression: полные регрессионные тесты
    cross_browser: кроссбраузерные тесты
    ui: тесты пользовательского интерфейса
    api: API-тесты
